apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      environment: production
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        environment: production
    spec:
      containers:
        - name: nginx
          image: nginx
